spring.application.name=reminders-api
server.port=9000
server.servlet.context-path=/api

#spring.data.mongodb.uri=mongodb+srv://root:root@tharun.gm2rp.mongodb.net/reminders_db?retryWrites=true&w=majority&appName=tharun
#spring.data.mongodb.database=reminders_db

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


logger.level.root=WARN
#logger.level.org.springframework.data.mongodb=DEBUG
